---
- name: "Provision New GCE CentOS Instance"
  hosts: "localhost"
  gather_facts: False
  vars:
    build_id: "{{ lookup('env', 'buildID') }}"
    credentials_file: "{{ lookup('env', 'GOOGLE_APPLICATION_CREDENTIALS') }}"
    ssh_public_key: "{{ lookup('file', lookup('env', 'GCP_SSH_PUBLIC_KEY')) }}"
  tasks:
  - name: "Provision Instance"
    register: "gce"
    gce:
      state: "present"
      disk_size: 30
      instance_names: "kubevirt-imagebuilder-gce-{{ build_id }}"
      project_id: "cnvlab-209908"
      zone: "us-central1-b"
      image_family: "centos-7"
      machine_type: "n1-standard-4"
      service_account_email: "push-button-ci@cnvlab-209908.iam.gserviceaccount.com"
      credentials_file: "{{credentials_file}}"
      metadata: '{"ssh-keys": "centos: {{ ssh_public_key }}"}'
      tags:
        - "kubevirtci"
  - name: "Write instance IP to /tmp/inventory"
    copy:
      content: '{{ gce.instance_data[0].public_ip }}'
      dest: "/tmp/inventory"
  - name: "Wait for SSH to become available"
    wait_for:
      host: "{{ gce.instance_data[0].public_ip }}"
      port: 22
      timeout: 620
      state: "started"
