---
- name: "Create Image From A Running GCE Instance"
  hosts: "localhost"
  gather_facts: "False"
  vars:
    build_id: "{{ lookup('env', 'buildID') }}"
    credentials_file: "{{ lookup('env', 'GOOGLE_APPLICATION_CREDENTIALS') }}"
    kubevirt_version: "{{ lookup('env', 'KUBEVIRT_VERSION') }}"
    ssh_public_key: "{{ lookup('file', lookup('env', 'GCP_SSH_PUBLIC_KEY')) }}"
  tasks:
  - name: "Shut Down Running Instance"
    gce:
      service_account_email: "push-button-ci@cnvlab-209908.iam.gserviceaccount.com"
      credentials_file: "{{ credentials_file }}"
      zone: "us-central1-b"
      project_id: "cnvlab-209908"
      instance_names: "kubevirt-imagebuilder-gce-{{ build_id }}"
      state: "stopped"
  - name: "Create Image From Disk"
    gcp_compute_image:
      state: "present"
      auth_kind: "serviceaccount"
      service_account_file: "{{ credentials_file }}"
      project: "cnvlab-209908"
      name: "kubevirt-labci-gce-{{ build_id }}"
      family: "kubevirt-labci-gce"
      description: "CI Generated Image For GCE Runs Of Labs on Kubevirt.io"
      disk_size_gb: 30
      source_disk:
        selfLink: "projects/cnvlab-209908/zones/us-central1-b/disks/kubevirt-imagebuilder-gce-{{ build_id }}"
  - name: "Deleting Source Instance"
    gce:
      service_account_email: "push-button-ci@cnvlab-209908.iam.gserviceaccount.com"
      credentials_file: "{{ credentials_file }}"
      zone: "us-central1-b"
      project_id: "cnvlab-209908"
      instance_names: "kubevirt-imagebuilder-gce-{{ build_id }}"
      state: "absent"
  - name: "Spin up google-sdk instance For Upcoming Publish Step"
    register: "gce"
    gce:
      state: "present"
      disk_size: 30
      instance_names: "kubevirt-imagepublisher-gce-{{ build_id }}"
      project_id: "cnvlab-209908"
      zone: "us-central1-b"
      image: "kubevirt-googlesdk"
      machine_type: "n1-standard-4"
      service_account_email: "push-button-ci@cnvlab-209908.iam.gserviceaccount.com"
      credentials_file: "{{credentials_file}}"
      metadata: '{"ssh-keys": "centos: {{ ssh_public_key }}"}'
      tags:
        - "kubevirtci"
  - name: "Write Publisher IP to /tmp/inventory"
    copy:
      content: '{{ gce.instance_data[0].public_ip }}'
      dest: "/tmp/inventory"
  - name: "Wait for SSH to become available"
    wait_for:
      host: "{{ gce.instance_data[0].public_ip }}"
      port: 22
      timeout: 620
      state: "started"
